Todo: fix loggin the run_tasks when debug is disabled

diff --git a/install b/install
--- a/install
+++ b/install
@@ -20,6 +20,9 @@ settings="$SCRIPT_INVOCATION_DIR/settings"
 source "$settings" 
 source "$configs"
 source "$lib_scripts"
+
+# Required to update the log path variable in the print debug script
+export LOG;
 # --------------------------------------------------------------------------------------- #
 
 
@@ -41,31 +44,31 @@ install_pacman_packages "$PREREQUISITES"
 # ------------------------------------ Install ------------------------------------ #
 run_tasks() {
 
-   install_yay  || exit $?
+   install_yay || exit $?
 
-   install_yay_packages "$YAY_PACKAGES"  || exit $?
+   install_yay_packages "$YAY_PACKAGES" || exit $?
 
-   install_pyenv "$TEMP_DOTFILES_INSTALL_PATH/.pyenv"  || exit $?
-   install_python_version "$TEMP_DOTFILES_INSTALL_PATH/.pyenv" "$PYTHON_VERSION"  || exit $?
-   create_python_venv "$TEMP_DOTFILES_INSTALL_PATH/.pyenv/versions/$PYTHON_VERSION/bin/python" "$TEMP_DOTFILES_INSTALL_PATH/.python-$PYTHON_VERSION-venv"  || exit $?
-   install_packages_in_venv "$PIP_PACKAGES" "$TEMP_DOTFILES_INSTALL_PATH/.python-$PYTHON_VERSION-venv"  || exit $?
+   install_pyenv "$TEMP_DOTFILES_INSTALL_PATH/.pyenv" || exit $?
+   install_python_version "$TEMP_DOTFILES_INSTALL_PATH/.pyenv" "$PYTHON_VERSION" || exit $?
+   create_python_venv "$TEMP_DOTFILES_INSTALL_PATH/.pyenv/versions/$PYTHON_VERSION/bin/python" "$TEMP_DOTFILES_INSTALL_PATH/.python-$PYTHON_VERSION-venv" || exit $?
+   install_packages_in_venv "$PIP_PACKAGES" "$TEMP_DOTFILES_INSTALL_PATH/.python-$PYTHON_VERSION-venv" || exit $?
 
-   install_nvm "$TEMP_DOTFILES_INSTALL_PATH/.nvm"  || exit $?
-   install_node_version "$TEMP_DOTFILES_INSTALL_PATH/.nvm" "$NODEJS_VERSION"  || exit $?
+   install_nvm "$TEMP_DOTFILES_INSTALL_PATH/.nvm" || exit $?
+   install_node_version "$TEMP_DOTFILES_INSTALL_PATH/.nvm" "$NODEJS_VERSION" || exit $?
+
+   install_oh_my_zsh "$TEMP_DOTFILES_INSTALL_PATH/.oh-my-zsh" || exit $?
 
    create_dirs "$HOME/.cache" "$WALLPAPERS_DIRECTORY" || exit $?
 
    get_env_vars "$settings" "$INSTALLATION_SETTINGS" "$INSTALLATION_DEFAULTS" "$INSTALLATION_ENVIRONMENT_VARIABLES" "$INSTALLATION_FILESYSTEM_MAPPING" "$VARS" "$TEMP_INSTALL_PATH/environment_variables.sh" || exit $?
    create_cookiecutter_project -e "$TEMP_INSTALL_PATH/environment_variables.sh" -t "$COOKIECUTTER_DOTFILES_VENV_TEMPLATE_DIR" -i "$TEMP_INSTALL_PATH" || exit $?
-   install_oh_my_zsh "$TEMP_DOTFILES_INSTALL_PATH/.oh-my-zsh" || exit $?
     
 }
 
 if [ "$ENABLE_DEBUG" = true ]; then
    gum spin --spinner dot --title "Installing all packages and tools..." -- sleep 1 && run_tasks
 else
-   if ! gum spin --spinner dot --title "Installing all packages and tools..." -- bash -c "$(declare -f); run_tasks";then
-      printf "%b" "${ERROR_COLOR}" 
+   if ! gum spin --spinner dot --title "Installing all packages and tools..." -- bash -c "$(declare -f); run_tasks";then printf "%b" "${ERROR_COLOR}" 
       echo "!!! An error occurred during installation. Try running again the installation in debug mode with the '-d' or '--debug' options. !!!"
       printf "%b" "${NO_COLOR}" 
       exit 1
